### ISSUE TITLE
[feature request][dmenu] read list from stdin

### ISSUE THREAD

**Issue by cinghiopinghio** [nwg-piotr/nwg-launchers#10]
This has now a very nice shape (much more responsive than the older python based ones).

Since you provide a command which emulate the old `dmenu-run` functionality, it would be very cool to see the normal behaviour of `dmenu`: provide a gui to select an item from a list.
This can help people to substitute `rofi` and `wofi` to build their scripts. (the latter is `wayland` prepared but has a very poor efficiency running at 100% CPU for few seconds for long lists).

In particular `dmenu` (and `rofi` and `wofi`) read a list from `stdin`, a different approach would be to read a `json` file from `stdin` such as the configuration file of `nwgbar`.

**Comment by nwg-piotr** [comment]
I was unsure if someone's going to be interested in such a feature. May be considered.

**Comment by cinghiopinghio** [comment]
I think many people that moved to sway are now looking for a valid alternative to `rofi` for all those scripts accumulated. the only other real alternative is `bemenu` which is a `dmenu` clone with few improvements.

**Comment by nwg-piotr** [comment]
Actually what I use instead of rofi is nwgbar with a couple of templates - Exit menu, and even a dock.

![Swappshot Sun Mar 22 15:34:26 2020](https://user-images.githubusercontent.com/20579136/77252172-c2d3cd00-6c52-11ea-836b-d5cc6cae33dc.png)

They look better than just a menu. But your idea remains interesting.

**Comment by nwg-piotr** [comment]
Alright. I think reading json from stdin makes few sense. I'd rather let people use their wofi-aimed scripts with no major changes. This would look something like this:

![2020-03-23-121307_screenshot](https://user-images.githubusercontent.com/20579136/77311614-befe8400-6d00-11ea-9216-44b0597fd43b.png)

This is my old Exit script for wofi. I only removed a cache-related line, as nwgdmenu uses no cache. You may build `nwgdmenu` from the development branch to give it a try.

**Comment by cinghiopinghio** [comment]
Hi, that's great, thanks.
I found a small weirdness:

when printing the output to a terminal it works as expected:
```
> find . -type f -name \*.pdf | head | nwgdmenu
xxx.pdf%
```

when piping the output to a new command I have:
```
> find . -type f -name \*.pdf | head | nwgdmenu | cat -
[
   {
     "success": true
   }
 ]
[
   {
     "success": true
   }
 ]
xxx.pdf%
```

**Comment by nwg-piotr** [comment]
Are you on sway? You probably see the output of swaymsg command. I'll check if I can redirect it to dev/null.

**Comment by cinghiopinghio** [comment]
Yes, I'm on sway!

**Comment by nwg-piotr** [comment]
`nwgdmenu` should be `--quiet` now. Please check if it behaves well on your side.
