### ISSUE TITLE
[request] Integration with Wayfire

### ISSUE THREAD

**Issue by epsilon-0** [nwg-piotr/nwg-launchers#108]
I am using these with Wayfire on Gentoo and these are really awesome!

I was wondering if it was possible to make the `nwgbar` integrate with wayfire as currently it doesn't support the logout button.

Thanks a lot.

**Comment by nwg-piotr** [comment]
With nwgbar you can define as many button bars as you need, with different content, styling, placement and orientation.

![mx.png](https://scrot.cloud/images/2020/08/30/mx.png)

What comes with the default installation is a sample exit menu for sway on Arch Linux. To give it another content, edit the `~/.config/nwg-launchers/nwgbar/bar.json` template. To give it another outlook, edit the `~/.config/nwg-launchers/nwgbar/style.css` style sheet.

For another template, use the `nwgbar -t your_template_name.json` command.

For another outlook, use the `nwgbar -c your_stylesheet_name.css` command.

Your custom templates and .css files must be placed in the `~/.config/nwg-launchers/nwgbar/` folder.

To adjust placement and orientation, use `-ha`, `-va` and `-v` arguments. More details in [README](https://github.com/nwg-piotr/nwg-launchers#nwgbar). Also `nwggrid -h` helps.

**Comment by epsilon-0** [comment]
These look beautiful  :star_struck: 
Unfortunately, wayfire delegates background setting to wf-shell which also adds a bar by default (hence would overshadow the nwgbar, unless I place it at bottom, which seems doable, as shown). I am going to start to play around with this, loving it so far!!!

**Comment by nwg-piotr** [comment]
I'm not really sure which background you mean. The screenshot above was taken on sway, but my current Wayfire setup looks exactly the same. Of course two instances of nwgbar can not be running at the same time. This picture was combined of 2 screenshots.

If by background you mean the wallpaper: I don't use default

```text
[autostart]
background = wf-background
```

but

```text
background = ~/.azotebg
```

The `~/.azotebg` script is being created by my [Azote](https://github.com/nwg-piotr/azote) wallpaper manager. It does not yet work well on Wayfire, but I'll be working on it tonight.

**Comment by nwg-piotr** [comment]
[This script](https://github.com/soreau/wayland-logout/blob/master/wayland-logout.py) by @soreau , launched with the logout button, works perfectly well.

**Comment by epsilon-0** [comment]
Awesome!!!
Thanks a lot, I will try this out as well.

**Comment by epsilon-0** [comment]
OK, seems like it is working, I wrote a smaller example using shell, in this PR - https://github.com/soreau/wayland-logout/pull/2
It is working very nicely :smile_cat:

**Comment by epsilon-0** [comment]
might I implore upon you to show how you made those cool effects for your launchers ?

**Comment by nwg-piotr** [comment]
LOL, which effects do you mean exactly?

**Comment by epsilon-0** [comment]
Yes, I did mean the styling.
Thanks so much !!!

**Comment by epsilon-0** [comment]
could you tell what your top and bottom bars are?

**Comment by nwg-piotr** [comment]
This is waybar. `wf-panel` and `wf-dock` look great, but seem to be in early stage of development, so I just copied my bars from sway.

**Comment by epsilon-0** [comment]
Indeed, they are very rudimentary.
I've not managed to make the background of nwgbar to be transparent for some reason, I keep getting a blackish background.

**Comment by nwg-piotr** [comment]
Could you show me the command?

**Comment by epsilon-0** [comment]
I just run `nwgbar`.
I've edited the default `style.css`

**Comment by epsilon-0** [comment]
```
$ nwgbar
4 bar entries loaded
WM: other
Using /home/aisha/.config/nwg-launchers/nwgbar/style.css
Focused display: 0, 0, 1920, 1080
Time: 122ms
```

**Comment by nwg-piotr** [comment]
The background can not be defined in the style sheet. You need the `-o 0.0` argument to make it transparent. Or `-b RRGGBBAA` for rgb with alpha.

**Comment by epsilon-0** [comment]
Oh, wow! 
I did not know that.
That seems a bit weird...?

**Comment by epsilon-0** [comment]
THAT WORKED!!!
Thanks a lot, I'll play around more now.

**Comment by nwg-piotr** [comment]
It simply didn't work well with css, so I decided to do it another way.

**Comment by nwg-piotr** [comment]
BTW: my Azote wallpaper manager finally seems to work well on Wayfire. I'm about to publish a new release.

https://www.reddit.com/r/Wayfire/comments/iqfket/wayfire_support_in_azote_wallpaper_manager

**Comment by epsilon-0** [comment]
Oh my, this is beautiful too :star_struck: 
I'll have to try that out too :smile_cat:

**Comment by nwg-piotr** [comment]
There's no Gentoo package so far, but this is python. You should be able to just clone and run. Let me know in case you need help.

**Comment by epsilon-0** [comment]
I am the package maintainer for quite a bit of wayland things in gentoo.
I'll add this as well :smiley_cat:

**Comment by nwg-piotr** [comment]
Great news! If so, I'll grab onemore coffee and release v1.7.14.

**Comment by epsilon-0** [comment]
OK, so I've packaged it and will make a request to put it in official tree - https://github.com/epsilon-0/wayland-desktop/tree/master/gui-apps/azote
But its been working quite nicely :smile_cat: 

The current error is something like this here - https://epsilonknot.xyz/recording.mp4
When I do `alt-tab` the background shown is the original background for some reason.

**Comment by nwg-piotr** [comment]
Pay attention to this: https://github.com/nwg-piotr/azote#wayfire

**Comment by epsilon-0** [comment]
Ah, snap, ok, I will have to do a lot more changes.
Thanks, will update in a bit.
