### ISSUE TITLE
Zoom icon does not show.

### ISSUE THREAD

**Issue by bernharl** [nwg-piotr/nwg-launchers#111]
The AUR package zoom-system-qt stores it's icon in /usr/share/pixmaps. Wofi's drunner finds this icon, but nwggrid does not. If it doesn't already, consider also searching in /usr/share/pixmaps?

**Comment by nwg-piotr** [comment]
You could add the path to XDG_DATA_DIRS, but yes: it could be also added in grid_tools.cc [line 101](https://github.com/nwg-piotr/nwg-launchers/blob/5c319532f0cd3ac4e058f045b98d62d03ee1f2a4/grid/grid_tools.cc#L101).

**Comment by bernharl** [comment]
I may have phrased my issue a bit weirdly. What I meant is that the Zoom desktop entry does show, but it has a missing icon (a question mark)

**Comment by nwg-piotr** [comment]
Ah, well... This location seems to be GTK incompatible. I may try to add a fallback.

**Comment by nwg-piotr** [comment]
Seems to work here. At least the Netflix icon shows up. Could you check if you see Zoom?

**Comment by bernharl** [comment]
The Zoom icon shows up now, thanks for the quick response :)

**Comment by nwg-piotr** [comment]
Very well. Closing.

**Comment by Siborgium** [comment]
The location is not GTK incompatible, IconTheme searches in it as it should. It is Zoom.desktop entry that is malformed.

Take a look [here](https://developer.gnome.org/icon-theme-spec/), at the `Icon Lookup` section, `LookupFallbackIcon` definition. Zoom.desktop sets `Zoom.png` as its icon name, so the loader tries `Zoom.png.png`, `Zoom.png.svg`, and so on. Atleast, that's what it seems to do.

Copying `/usr/share/applications/Zoom.desktop` to `$XDG_DATA_HOME/applications/Zoom.desktop` and changing `Icon=Zoom.png` to `Icon=Zoom` fixes the problem.

**Comment by nwg-piotr** [comment]
There are more icons in my `/usr/share/pixmaps`. I've never ever installed Zoom, but e.g. Netflix stores its icon in the same place. If  it can work, I want it to work.

Also, your PR reintroduces #114, which I fixed two times so far.
