### ISSUE TITLE
Feature request : nwggrid to look for .desktop files in a specific directories

### ISSUE THREAD

**Issue by snakedye** [nwg-piotr/nwg-launchers#122]
nwggrid -d ~/.special/

**Comment by nwg-piotr** [comment]
I'm not sure if it makes sense, but is doable.

**Comment by snakedye** [comment]
I want to use nwggrid as some sort of launcher to a library with .desktop files executing zathura /path/to/book.

**Comment by snakedye** [comment]
Pretty much that yeah

**Comment by nwg-piotr** [comment]
All right, I'll take care of it soon.

**Comment by nwg-piotr** [comment]
> I want to use nwggrid as some sort of launcher to a library with .desktop files executing zathura /path/to/book.

Could you show me an example .desktop file? `nwggrid` cuts out some arguments.

**Comment by nwg-piotr** [comment]
Could you please build from the `special` branch and tell me if it works for you?

**Comment by snakedye** [comment]
![image](https://user-images.githubusercontent.com/49378990/96387876-53d03f80-1173-11eb-9653-437add749523.png)
I have the git version installed but I don't see the `-d` argument as option.

**Comment by nwg-piotr** [comment]
You'd need to `git clone -b special https://github.com/nwg-piotr/nwg-launchers.git` and build as described in README. Or I can just merge it into `master`, so that you could check by updating the -git package.

**Comment by snakedye** [comment]
Could you merge it?

**Comment by nwg-piotr** [comment]
In a minute.

**Comment by nwg-piotr** [comment]
You need to install `azote-git` over the current package, as I haven't bumped the version.

**Comment by snakedye** [comment]
It works!!!
![image](https://user-images.githubusercontent.com/49378990/96388474-005ff080-1177-11eb-8101-187f44565aab.png)

**Comment by nwg-piotr** [comment]
Excellent. :)

**Comment by nwg-piotr** [comment]
At least for now, the `-d <path>` argument will disable `-p`inned and `-f`avorites, as it clears the cache.

**Comment by snakedye** [comment]
I noticed it only works with path without spaces.

`nwggrid -d '/home/$USER/pathtofile'` works but `nwggrid -d '/home/$USER/path to file'` or `nwggrid -d '/home/$USER/path\ to\ file'` doesn't.

**Comment by nwg-piotr** [comment]
Arguments string is space-separated. For this to work with spaces, we would need another separator, e.g. colon: 

`-d /my/path:/my/another/path:/third/path`

Who on earth uses spaces in directory names?

**Comment by nwg-piotr** [comment]
OK, as it's 3:36 am in my place:

`-d '/my/path1:/my/another path:/third/path'`

is currently the proper format.

**Comment by snakedye** [comment]
I still can figure out how the -d argument works.

`nwggrid -d '/home/bryan/.mangas/Chainsaw Man/.chapter/:/home/bryan/.mangas/Fire Punch/.chapter/'` returns the desktop files for both directories, nice.

`nwggrid -d '/home/bryan/.mangas/Golden Kamuy/.chapter/:/home/bryan/.mangas/Shuukan Brick/.chapter/' only return the desktop files in the first directory. I tried swapping both an come to the same result.

It gets even weirder when I put more than 2 directories
`nwggrid -d '/home/bryan/.mangas/Chainsaw Man/.chapter/:/home/bryan/.mangas/Golden Kamuy/.chapter/:home/bryan/.mangas/Shuukan Brick/.chapter/' only shows Chainsaw Man and the second directory but
``nwggrid -d '/home/bryan/.mangas/Shuukan Brick/.chapter/:/home/bryan/.mangas/Golden Kamuy/.chapter/:/home/bryan/.mangas/Chainsaw Man/.chapter/:'` shows Chainsaw Man and Shukkan Brick.

From what I experience Chainsaw Man and Fire Punch always show up but the directories for other mangas are always skipped.

Depending on the order some directories aren't completely listed.
```
manga_menu() {
  args=""
  cd ~/.mangas
  ls -r ./ | while read manga
  do
    args+="/home/$USER/.mangas/$manga/.chapter/:"
  done
  args="$(echo "$args" | sed "s/:$//")"
  echo nwggrid -d '"'$args'"' -s 250
  nwggrid -d '"'$args'"' -s 200 -o 0.9 -b 434c5e
}
```
I used this script for some of the testing

**Comment by nwg-piotr** [comment]
I'm afk at the moment, but have you tried not to use trailing "/"?

**Comment by nwg-piotr** [comment]
Trailing slashes make no difference.

I've added a simple validity check. Returns [OK] if the path exists and is a directory.

```
$ nwggrid -d '/home/piotr/.special case:/home/piotr/.local/share/applications:some/other/screwed path'
WM: other
Locale: pl

Using custom .desktop files path(s):
'/home/piotr/.special case' [OK]
'/home/piotr/.local/share/applications' [OK]
'some/other/screwed path' [INVALID]

Using /home/piotr/.config/nwg-launchers/nwggrid/style.css
Focused display: 0, 0, 1920, 1080
Total: 117ms
	grids:   1ms
	boxes:   3ms
	images:  17ms
	bs:      96ms
	commons: 0ms
```
Merged, please reinstall.

**Comment by snakedye** [comment]
https://imgur.com/a/janQMr2

All directories are okay but some are skipped and the not all desktop files are listed. It also varies on how arguments are listed. The first example was with ls -r in the manga_menu function and the second one with ls.

**Comment by nwg-piotr** [comment]
Look into `.desktop` files. If some of them contain the `NoDisplay=true`line, they won't be shown. I checked the code in several ways, and it would always behaved well here.

**Comment by snakedye** [comment]
All my desktop files look like this:

[Desktop Entry]
Type=Application
Name=$NEW Ch.$2
Icon=/home/$USER/.mangas/.covers/$NEW.jpg
Exec=cd $dir ; ls ./ | imv
Categories=Manga" > ~/.mangas/$NEW/.chapter/c$2.desktop

I've tried deleting everything and reinstalling it with the function I use on my desktop which doesn't show this issue to this extent (for some reason there's a chapter that never shows up there) and nothing changed. There seem to be no error with way the command is formatted but it never shows everything.

**Comment by nwg-piotr** [comment]
No idea what the output of the script may look like, but it must be the culprit. Regular .desktop files behave as they should. Hint: if a .desktop file has no Name or Exec, it won't be shown in nwggrid.

**Comment by snakedye** [comment]
https://www.youtube.com/watch?v=tlUVbO8JqNQ

https://www.youtube.com/watch?v=Yv1TUBnmMv4

Individually they all show up. It doesn't work manually or with a script. Have you tested this on your devices?

**Comment by nwg-piotr** [comment]
Sorry, I don't understand what's going wrong on your side. When given colon-separated absolute full paths, nwggrid displays all valid .desktop files. 

> An absolute path refers to the complete details needed to locate a file or folder, starting from the root element and ending with the other subdirectories.

**Comment by snakedye** [comment]
I think I'll just symlink all the desktop files in the same folder.

**Comment by snakedye** [comment]
I fixed it, it was due files sharing the same name.

**Comment by nwg-piotr** [comment]
Very well. Please close it you find the resolved.
