### ISSUE TITLE
How is a terminal chosen for .desktop files with Terminal=true ?

### ISSUE THREAD

**Issue by epsilon-0** [nwg-piotr/nwg-launchers#127]
Currently no terminal UI based applications (e.g. htop) can be started.

**Comment by nwg-piotr** [comment]
It's unsupported, at least for now. TBH I know no universal method to check the default terminal. Ideas?

**Comment by epsilon-0** [comment]
There is none...
This a big hole in freedesktop sepcifications of .desktop files.
This (among many other such threads) was the state of setting and finding terminal application:
https://xdg.freedesktop.narkive.com/bL3IsaJQ/spec-to-define-the-default-terminal#post11

How gnome does the finding is just cancerous
https://gitlab.gnome.org/GNOME/glib/-/blob/master/gio/gdesktopappinfo.c#L2548

My simple solution (though not universal or "adhering to [nonexistent] standards"): add it as a option in the config file.
Something like - `terminal_exec_command: "alacritty -e "`, which will run - `alacritty -e "{command from Exec=}"`

Because the current "solution" that everyone uses is to add the above `alacritty -e` to the start of the `Exec=` command.
This was it is atleast centralized and easily configurable.

Freedesktop specifications are a swiss cheese block, this one is just another hole.

**Comment by nwg-piotr** [comment]
I'll try detecting several mostly used emulators, and save the first found one's name to `~/.config/nwg-launchers/term` txt file for further use. The user will be able to replace it with their preferred terminal.

**Comment by nwg-piotr** [comment]
I've added a [function](https://github.com/nwg-piotr/nwg-launchers/blob/52f0f83f1349d94b4ae6a9267f4447e0894f724a/common/nwg_tools.cc#L90) to detect the installed terminal emulator. It loops though 6 `<terminal> -v` commands, until one of them returns exit code 0, and saves the terminal name to the `~/.config/nwg-launchers/nwggrid/term` file. In case it doesn't happen, the `xterm` name is being saved, regardless of whether it is installed or not. In both cases users may edit the `term` file content to use their favorite terminal emulator.

If you know any other terminal emulator with a command, which returns 0 exit code and terminates, it may be added to the list. AFAIK `st`, `sakura` and `gnome-terminal` have no such command (`st` and `sakura` return 1).

If you'd like to test changes, please build from the `term` branch.

**Comment by epsilon-0** [comment]
will do tonight.

**Comment by nwg-piotr** [comment]
It turns out that there's a [much better way](https://stackoverflow.com/a/677212/4040598) to check the command availability, which I was unaware of (stupid me!). Now we can check any terminal we want.
