### ISSUE TITLE
Nwggrid doesn't sort .desktop files with names longer than 27 characters

### ISSUE THREAD

**Issue by gingkapls** [nwg-piotr/nwg-launchers#128]
Whenever you create a .desktop file with a name which nwggrid shortens, the sorting gets botched up.

To reproduce this bug, just create a few .desktop files with name fields more than 27 characters long, and add numbers at the end respectively like this:

File 1: "name that is  more than 27 chars long 01"
File 2: "name that is more than 27 chars long 02"
File 3: "name that is more than 27 chars long 03"
File 4: "name that is more than 27 chars long 04"
and so on
Normally file 1 should be displayed before file 2, but since the application doesn't seem to parse characters after the 27 char limit, the files aren't in alphanumeric order.

Using nwggrid 0.4.0 latest from aur.

**Comment by gingkapls** [comment]
https://github.com/nwg-piotr/nwg-launchers/blob/fae9f8f2fc972fc5144a97337d42e4cb33298b2e/grid/grid_classes.cc#L353-L355

Increasing the name.length value does fix the sorting issue, but it also ends up displaying the whole name of the entry.
Perhaps shortening the string when displaying but still use the whole string for sorting would be ideal I guess.

**Comment by nwg-piotr** [comment]
> Perhaps sorting the files first and then shortening the string would be ideal?

It is not feasible, as we use the built-in [Gtk::FlowBox::set_sort_func](https://developer.gnome.org/gtkmm/stable/classGtk_1_1FlowBox.html#a92de4edbfa01f217e60fe613902b4532) method. I'll add a workaround with a helper string variable.

**Comment by gingkapls** [comment]
> I'll add a workaround with a helper string variable.

Thanks! It works wonderfully, now even the files with longer names are sorted properly.

**Comment by nwg-piotr** [comment]
Excellent! I'll merge it into master as soon as the other changes (#127) are tested.
