### ISSUE TITLE
nwggrid randomly opens apps in terminal

### ISSUE THREAD

**Issue by Evo221** [nwg-piotr/nwg-launchers#132]
I found that nwggrid randomly opens some apps in a terminal even if the desktop file does not specify
```
Terminal=true
```
This seems to be because of an uninitialised variable. A fix that works for me is at https://github.com/nwg-piotr/nwg-launchers/pull/131

**Comment by nwg-piotr** [comment]
It hasn't happened to me so far, but obviously the field should be initialized.
