### ISSUE TITLE
Two issues with terminal selection.

### ISSUE THREAD

**Issue by Evo221** [nwg-piotr/nwg-launchers#134]
1. Although common, it seems that the -e option for a terminal to run a command is not universal.
I discovered this after opening an issue for the foot terminal emulator. See
https://codeberg.org/dnkl/foot/issues/184

2. The code that calls "command -v" redirects the output to /dev/null with "&>/dev/null". While this will work for bash, for other shells such as dash (default on Debian) this redirection will not work and as a quite unfortunate side effect the call to ```std::system()``` will return 0 even if the exit status for "command -v foo" is non-zero.

I prepared a pull request for this. The branch has thee commits. The first two fix the issues above and the third
adds the foot terminal emulator to the list of terminals to try. See https://github.com/nwg-piotr/nwg-launchers/pull/136

**Comment by nwg-piotr** [comment]
I installed foot from AUR, and it seems half-baked to me. IMO it should behave as other terminals do: accept the `-e` flag. Furthermore, I applied your PR locally and the only command that runs in htop here is vim. For instance:

> $ nwggrid -p
WM: sway
Locale: pl
6 pinned entries loaded
Using /home/piotr/.config/nwg-launchers/nwggrid/style.css
Focused display: 1920, 0, 1920, 1080
Total: 205ms
	grids:   16ms
	boxes:   17ms
	images:  48ms
	bs:      119ms
	commons: 5ms
Running: 'foot htop &'
info: main.c:345: version: 1.5.3
info: main.c:352: arch: x86_64/64-bit
info: config.c:1979: loading configuration from /home/piotr/.config/foot/foot.ini
info: main.c:369: locale: pl_PL.UTF-8
[piotr@msi nwg-launchers]$ info: wayland.c:1076: eDP-1: 1920x1080+1920x0@120Hz 0xD0ED 15.33" scale=1 PPI=147x154 (physical) PPI=147x154 (logical), DPI=143.66
info: wayland.c:1076: DP-1: 1920x1080+0x0@60Hz 22V2WG5 21.68" scale=1 PPI=106x108 (physical) PPI=106x108 (logical), DPI=101.60
info: wayland.c:1076: HDMI-A-1: 1920x1080+3840x0@60Hz 2243W 21.68" scale=1 PPI=106x108 (physical) PPI=106x108 (logical), DPI=101.60
info: wayland.c:1212: requesting SSD decorations
info: fcft.c:245: fcft: 2.3.1
info: fcft.c:255: fontconfig: 2.13.91
info: fcft.c:261: freetype: 2.10.4
info: fcft.c:671: /usr/share/fonts/TTF/DejaVuSansMono-Oblique.ttf: size=8.00pt/15px, dpi=143.66
info: fcft.c:671: /home/piotr/.local/share/fonts/AL DejaVuSansMono-Bold.ttf: size=8.00pt/15px, dpi=143.66
info: fcft.c:671: /home/piotr/.local/share/fonts/AL DejaVuSansMono.ttf: size=8.00pt/15px, dpi=143.66
info: fcft.c:671: /usr/share/fonts/TTF/DejaVuSansMono-BoldOblique.ttf: size=8.00pt/15px, dpi=143.66
info: terminal.c:615: cell width=9, height=18
info: terminal.c:553: using 8 rendering threads
info: wayland.c:660: using SSD decorations
[piotr@msi nwg-launchers]$ info: main.c:513: goodbye

Most commands like e.g. `foot neoftech &` show up in the foot window and immediately disappear. Tested in sway.

**Comment by Evo221** [comment]
Hmm, foot 1.5.2 on Debian works very well for me. There are packages for Debian testing and unstable and I backported them to Debian stable - which I'm currently using. 

Under Sway, nwggrid from my fix-term branch works perfectly with "foot" and "urxvt -e" tested with htop, mutt, mc and vim. Basically any "Terminal=true" desktop files that I have. What programs did it fail with?

Maybe it's an issue with foot 1.5.3 or the AUR package.

**Comment by nwg-piotr** [comment]
You're right. But it does not explain why htop and mc say "goodbye" to me in foot.

**Comment by nwg-piotr** [comment]
One more thing: if your PR is merged, running in the terminal will stop working for all the people running nwg-launchers>=0.4.1. You'd need to remove the `~/.config/nwg-launchers/nwggrid/term` file if exists, and create another one, possibly under another name.

**Comment by Evo221** [comment]
What about something like he following - written in bash for clarity (not actually suggesting it is implemented in bash)
```
old=$HOME/.config/nwg-launchers/nwggrid/term
new=$HOME/.config/nwg-launchers/nwggrid/terminal

if [[ -f $old && ! -f $new ]] ; then
    sed 's/$/ -e/' < $old > $new
fi
```
Then nwggrid can just act as it does now except it should read and write $new instead of $old.

**Comment by nwg-piotr** [comment]
No need for external scripts. After creating the new file (if not found), nwggrid should just check if the old file exists, and delete it if so. 3 lines of code.

**Comment by Evo221** [comment]
Sorry I didn't mean to imply it should be done by a bash script, I was just trying to use that as pseudo code to illustrate what I was proposing. I'd suggest not deleting the old $HOME/.config/nwg-launchers/nwggrid/term it would break the users config if for some reason they downgraded nwg-launcher at some point.

I updated my branch with these changes (the forced pushes were to fix white space issues without polluting the history).

**Comment by nwg-piotr** [comment]
>  it would break the users config if for some reason they downgraded nwg-launcher at some point

Nope. If not found, the file will be re-created.

**Comment by Evo221** [comment]
It would be recreated with a value that is possibly different to what the user set it to. That's what I mean by breaking the users config.

**Comment by nwg-piotr** [comment]
It is highly unlikely that even a single user would want to downgrade the package. I'd rather not to leave junk files in the config folder.

**Comment by Evo221** [comment]
Ok, fair enough. Branch updated.

**Comment by nwg-piotr** [comment]
All right. I'll take a closer look at it in the evening, as I'm at the office now.

**Comment by dnkl** [comment]
> Most commands show up in the foot window and immediately close. Tested in sway and Wayfire.

@nwg-piotr did you install the terminfo files (https://aur.archlinux.org/packages/foot-terminfo)? If foot says "goodbye" without any other warnings or errors, it means the client application (i.e. htop) exited normally. In this case a likely cause is missing terminfo files. You could always try running `foot --hold htop` to see if htop is printing some kind of error message before exiting.

As an example, if i run `foot --hold --term=foobar htop`, htop prints:
```
Error opening terminal: foobar.
```

**Comment by nwg-piotr** [comment]
> did you install the terminfo files?

Building ends up in the error:

```
error: target not found: foot-terminfo
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> foot-terminfo
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
:: Unable to build foot-terminfo - makepkg exited with code: 8
```

**Comment by dnkl** [comment]
@nwg-piotr my bad. Up until yesterday, `foot-terminfo` was only an _optional_ dependency for `foot`. Yesterday I changed that to make it a hard dependency, to prevent others from making the same mistake. But I obviously failed to do it correctly (`foot` and `foot-terminfo` are built from the same `PKGBUILD`).

That should be fixed now. Sorry about that.

**Comment by nwg-piotr** [comment]
I confirm: it works now, including htop.

**Comment by nwg-piotr** [comment]
@dnkl I updated README. Thanks for fixing foot in AUR.
