### ISSUE TITLE
garbled text in reboot icon

### ISSUE THREAD

**Issue by epsilon-0** [nwg-piotr/nwg-launchers#137]
I've not been able to see the reboot icon properly.

This is what I get:
![20201111_16h05m42s_grim](https://user-images.githubusercontent.com/8932410/98864418-d927d680-2437-11eb-8ac1-c1e129804274.png)

**Comment by epsilon-0** [comment]
Also it seems like the icons are set to blue color for some reason.
How would I go about changing the `style="fill:#3875d6;fill-opacity:1"` option for the SVG files?

**Comment by epsilon-0** [comment]
I fixed the garbled problem!
I am still not sure how to change colors of svg from nwgbar.

**Comment by nwg-piotr** [comment]
This icon must have been saved as text. Conversion to curves in Inkscape should help. Also icon colours are defined in the svg file. Feel free to edit them to your liking.
