### ISSUE TITLE
[Request] WLR Layer Shell protocol support?

### ISSUE THREAD

**Issue by epsilon-0** [nwg-piotr/nwg-launchers#138]
This way, the bar/grid/dmenu can have animations disabled.

Currently, on wayfire, the bar and grid have animation effects (fire animation) just like rest of the windows.

Potentially, we don't want the bar and grid to have animations, and can probably put them in the `overlay` layer so that they are on top?

**Comment by nwg-piotr** [comment]
Firstly: the program is expected to work on X11 as well, not only on Wayland. Secondly: this would be a really major rework. I'd rather write everything from scratch.

**Comment by epsilon-0** [comment]
Ah, damn. Well, that's a fair point :+1: 
Thanks for the answer.

**Comment by epsilon-0** [comment]
I got a workaround by creating using application id for ignoring animations
Here's some cool pix for your pleasure, feel free to use them however you want.
nwgbar - https://i.imgur.com/o1hd4zz.png
nwggrid - https://i.imgur.com/JVaGhy0.png

**Comment by nwg-piotr** [comment]
Haha, thanks! it looks great.

BTW: I like my grid and bar with the Zoom animation.

**Comment by Siborgium** [comment]
Actually I was thinking whether I should try to use layer-shell. I am busy right now, but I'd be happy to implement this in future. This won't have any impact on X11 compatibility, it's not a big deal to handle both variants. GTK is main problem, but I am sure there should be a way to build Gdk Window on layer-shell surface.

**Comment by nwg-piotr** [comment]
According to @alebastr it should be no problem. See #140. I'd prefer this to be done by a skilled C++ developer. I focused on golang lately, and made no progress in C++.
