### ISSUE TITLE
Check $TERMINAL and/or $TERMCMD

### ISSUE THREAD

**Issue by Siborgium** [nwg-piotr/nwg-launchers#139]
Regarding `get_term` function: I advise you to check `$TERMINAL` and/or `$TERMCMD` first, and only if this fails, fallback to config/predefined values. Although the variables are not standard, they are widely used, as noted in [this](https://bugs.freedesktop.org/show_bug.cgi?id=92514) discussion.

**Comment by nwg-piotr** [comment]
LOL, it reminds me of setting GTK themes in Wayfire: you need to `export GTK_THEME=Your-Theme`. Seriously? What stops the from reading `gtk.ini`?

Anyway, thank you for the advice. It may be worth of try.

**Comment by Siborgium** [comment]
In general, checking the variables first allows one to override settings.ini (e.g. temporarily).

**Comment by nwg-piotr** [comment]
Agreed. I'll add this feature.
