### ISSUE TITLE
Launcher are in windows on river

### ISSUE THREAD

**Issue by snakedye** [nwg-piotr/nwg-launchers#140]
https://gofile.io/d/7Ngsxi

(my fetch is lying)

**Comment by nwg-piotr** [comment]
The background is a semi-transparent window, everywhere. I know nothing about river. A window manager?

**Comment by snakedye** [comment]
It's a tiling Wayland compositor.

>The background is a semi-transparent window

Wouldn't it be more appropriate to use the layer shell protocol?

**Comment by nwg-piotr** [comment]
> Wouldn't it be more appropriate to use the layer shell protocol?

As I said earlier: this would be too fundamental change to the existing code. Maybe one day I'll try to code the grid and the bar from scratch. Preferably in golang, as I don't really like C++.

**Comment by alebastr** [comment]
I had my doubts regarding that fundamental change and it took only 30 lines of code and 15 minutes to make nwggrid work with layer shell: https://github.com/alebastr/nwg-launchers/commit/layer-shell.

It _probably_ doesn't break any of X11 window managers or unsupported wayland compositors, requires very latest gtk-layer-shell and absolutely not tested outside of sway, but I won't have time to do that until this or even next weekend :smiley: 
.

**Comment by nwg-piotr** [comment]
Feel free to PR when ready.

**Comment by nwg-piotr** [comment]
Should be resolved with #150
