### ISSUE TITLE
Sway window borders gone when launching one of nwg-launchers.

### ISSUE THREAD

**Issue by lemniskett** [nwg-piotr/nwg-launchers#146]
As the title said.
I'm not entirely sure if it's sway's issue or nwg-launcher's issue, but this doesn't happen with wofi, and wldash.
When launching one of nwg-launchers via terminal or keybinding, the active window border gone.

**Comment by lemniskett** [comment]
Here's a video of it
https://user-images.githubusercontent.com/43294321/103505216-4a11ca80-4e8c-11eb-828a-fb7c471f72f9.mp4

**Comment by nwg-piotr** [comment]
Which version are you running?

**Comment by lemniskett** [comment]
I'm running the latest version from nixpkgs-wayland repository for Nix OS, which is currently built from commit [976a5f311cd99658755089d5024b8980f73ea19a](https://github.com/nwg-piotr/nwg-launchers/commit/976a5f311cd99658755089d5024b8980f73ea19a)

**Comment by nwg-piotr** [comment]
It should be resolved with #147
