### ISSUE TITLE
Makefile from nwgdmenu does not properly clean

### ISSUE THREAD

**Issue by Madic-** [nwg-piotr/nwg-launchers#15]
The "clean" part in the nwgdmenu Makefile tries to remove "dmenu" instead of "nwgdmenu". I think there is a typo ;)
Original dmenu/Makefile:
```
clean:
        rm -rf *.o dmenu
```
Should be
```
clean:
        rm -rf *.o nwgdmenu
```

**Comment by nwg-piotr** [comment]
You're right. Thanks for pointing it out.

**Comment by nwg-piotr** [comment]
merged
