### ISSUE TITLE
.desktop description doesn't create a line break when overflows in nwggrid.

### ISSUE THREAD

**Issue by lemniskett** [nwg-piotr/nwg-launchers#151]
As the title says, also nwggrid expands beyond my screen when that happens

**Comment by lemniskett** [comment]
https://user-images.githubusercontent.com/43294321/104115512-bf751380-5342-11eb-997e-f7a12533847d.mp4

**Comment by nwg-piotr** [comment]
LOL, I've never ever expected such a log description! :rofl: All right, we'll truncate long ones.

**Comment by lemniskett** [comment]
Ahaha, indeed that's a really long description.

**Comment by nwg-piotr** [comment]
Let me fix it tomorrow. I'm thinking in golang at the moment. Just between us: I hate C. :wink:
