### ISSUE TITLE
Pressing enter for the first result in nwgdmenu isn't working with 0.4.3

### ISSUE THREAD

**Issue by ericonr** [nwg-piotr/nwg-launchers#152]
If I have one or more available results in nwgdmenu, I can't just press enter to select it (it doesn't do anything), I have to press the down arrow key (which doesn't actually move the selection box) and then I can press enter. If I narrow down the search enough so that there is a single result, then pressing enter without any arrows works.

I can try to track this down, just wanted to make it known.

**Comment by nwg-piotr** [comment]
I couldn't resolve this problem, seemed to be a GTK feature. Feel free to give it another chance.

**Comment by Siborgium** [comment]
Try [this](https://github.com/Siborgium/nwg-launchers/tree/enhance-dmenu) branch, I hope it'll help. Note that there is a subtle bug -- initially there is no selection, but once you type something, it'll work properly; but it should be easy to fix.
