### ISSUE TITLE
nwgdmenu error: gtk_main_quit: assertion 'main_loops != NULL' failed

### ISSUE THREAD

**Issue by Head-on-a-Stick** [nwg-piotr/nwg-launchers#153]
Running Alpine Linux ([my package](https://pkgs.alpinelinux.org/packages?name=nwg-launchers&branch=edge)) and trying to start [stone-soup](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/stone-soup) (also my package) the program doesn't start and I see this when I run `nwgdmenu` from a terminal:
```
(nwgdmenu:24842): Gtk-CRITICAL **: 18:09:29.433: gtk_main_quit: assertion 'main_loops != NULL' failed
```
The program launches fine via `nwggrid`.

**Comment by nwg-piotr** [comment]
Are you sure you're running `crawl-tiles`? After typing "stone" in the search box, I see just one result: "eddystone", and after I press enter, it ends up in:

> Low Energy Eddystone utility ver 5.55
> Failed to open HCI user channel
>
> (nwgdmenu:21620): Gtk-CRITICAL **: 21:42:20.199: gtk_main_quit: assertion 'main_loops != NULL' failed

but this is not the game you're talking about:

```text
[Desktop Entry]
Version=1.0
Type=Application
Name=Dungeon Crawl Stone Soup
Comment=Open-source, single-player, role-playing roguelike game of exploration and treasure-hunting
Exec=crawl-tiles
Icon=stone-soup
Terminal=false
StartupNotify=false
Categories=Application;Game;AdventureGame;
```

Selecting `crawl-tiles` from the menu launches the game.

![image](https://user-images.githubusercontent.com/20579136/105903441-2ae80200-6020-11eb-8d47-165609903032.png)

**Comment by Head-on-a-Stick** [comment]
Sorry, I should have been more clear — I type `craw` into the search box and I see both `crawl` (the terminal version) and `crawl-tiles` (the graphical version) in the selection area, the error is encountered when I scroll down to `crawl-tiles` and select that.

I've just discovered that if I type in `crawl-` (so that only `crawl-tiles` is available as an option) then the program will launch so the problem appears to arise from the availability of both `crawl` & `crawl-tiles` as options.

**Comment by Siborgium** [comment]
Try [this](https://github.com/Siborgium/nwg-launchers/tree/enhance-dmenu) branch, I hope it'll help.

**Comment by Head-on-a-Stick** [comment]
Yes, that version works. What did you change? I can patch the Alpine, Debian & Ubuntu packages for now.

**Comment by nwg-piotr** [comment]
@Head-on-a-Stick  It seems we're not yet ready with a new release.

**Comment by Siborgium** [comment]
Well, these changes have nothing to do with layer-shell, so I guess we can merge it into the master. I'll open separate PR in a few minutes.

**Comment by nwg-piotr** [comment]
@Head-on-a-Stick - fixes by @Siborgium merged and released.
