### ISSUE TITLE
swaywm - nwggrid ignores waybar

### ISSUE THREAD

**Issue by brzegorz** [nwg-piotr/nwg-launchers#155]
![image](https://user-images.githubusercontent.com/23345044/110315091-10cf1580-8009-11eb-920b-e6f9bbfa4a4d.png)

**Comment by nwg-piotr** [comment]
For now you can only use the bottom layer in Waybar, for nwggrid to show up on top. Next version should support `gtk-layer-shell`, but it's still a work in progress. #150

**Comment by nwg-piotr** [comment]
Should be resolved with #150
