### ISSUE TITLE
Log to stderr instead of stdout

### ISSUE THREAD

**Issue by crabvk** [nwg-piotr/nwg-launchers#158]
Scripts like `makoctl menu` expect selected variant (notification action) to be [printed to stdout](https://github.com/emersion/mako/blob/e5b5d56aaaf8390c97a17c208f950803538e7294/makoctl#L117).
When I call `makoctl menu nwgdmenu -n` it immediately shows error:
```log
/usr/bin/makoctl: No actions found
```
because it misinterpret log entry
> Using "/home/user/.config/nwg-launchers/nwgdmenu/style.css

as selection.

**Comment by nwg-piotr** [comment]
I wouldn't like to change anything in the current master branch until #150 is ready and merged. It's up to @Siborgium when it's going to happen.
