### ISSUE TITLE
Can the search bar size be configured? 

### ISSUE THREAD

**Issue by eulertour** [nwg-piotr/nwg-launchers#161]
Adding a `width` or `height` parameter to the `#searchbox` section of `style.css` results in `terminate called after throwing an instance of 'Gtk::CssProviderError'`. Is there another way to configure the size of the search bar?

**Comment by nwg-piotr** [comment]
You can't set width / height of the widget with css. It would be doable with [gtk.Widget.set_size_request](https://developer.gnome.org/pygtk/stable/class-gtkwidget.html#method-gtkwidget--set-size-request), but we can not implement size customization for every widget.

**Comment by eulertour** [comment]
Then is it only doable by editing the source code?

**Comment by nwg-piotr** [comment]
Yes. And it applies to every GTK3 widget.

**Comment by eulertour** [comment]
Ok, thanks for letting me know.
