### ISSUE TITLE
Improve speed by running in the background

### ISSUE THREAD

**Issue by ozls** [nwg-piotr/nwg-launchers#163]
Hello, first of all congrats for a great project. This was the missing piece for me to comfortably use Sway in all circumstances, and I am using it a lot. I have a simple suggestion, I don't know if you'd be interrested. Would it be possible to improve the responsiveness by making nwg-grid, for instance, run in the background ? In such a context, the grid would already be ready when the user launches the command, and it could appear very quickly. To be fair it doesn't take very long to load presently, but on my very fast laptop it's still about half a second and I feel it.

**Comment by nwg-piotr** [comment]
Possible, but the content would run out of date sometimes, when you install/uninstall packages.

**Comment by ozls** [comment]
I have some idea but I don't know what would be the easiest way: check for new apps in the background every few minutes? Or launch the app very quickly, displaying apps from cache, and then update the view while the user is already in it?

**Comment by nwg-piotr** [comment]
The safest way would be just to kill the app (manually?) after installing/uninstalling a package.

One way or another, I'll add no more feature to this certain project (see [this statement](https://github.com/nwg-piotr/nwg-launchers#this-project-is-community-driven)). If you want to submit a feature request, please take a look at the [nwg-shell](https://github.com/nwg-piotr/nwg-shell) project. The counterpart to the `nwggrid` command is [nwg-drawer](https://github.com/nwg-piotr/nwg-drawer).

**Comment by ozls** [comment]
Yes, I saw the statement briefly after posting my issue. Sorry about that, and many thanks for a great project!

**Comment by Siborgium** [comment]
I had this feature implemented in the past and can confirm it works. There are issues, but they're mostly solvable (e.g. we could add inotify watcher to app directories). I hope I'll manage to restore the code I had back then and make it work. No promises though.

**Comment by nwg-piotr** [comment]
@Siborgium How do you want to call the hidden windows back? For now only `GTK_LAYER_SHELL_KEYBOARD_MODE_EXCLUSIVE` seems to work with wlroots.

**Comment by Siborgium** [comment]
Idk actually, I tried this before layer-shell. There should be a way, and if there isn't we can just destroy & re-create the window, it would be still faster.

**Comment by nwg-piotr** [comment]
In nwg-dock, which optionally works this way, I just used a "hotspot" - an invisible window, that still exists on the screen to show the GUI back. Here we would need a key binding, but we can't access the keyboard.

**Comment by Siborgium** [comment]
Essentially:

 - Setup application, running in the background (nwg-grid-daemon);
 - Starting nwg-grid simply sends SIGUSR1 to nwg-grid-daemon or runs
   one;
 - nwg-grid-daemon on SIGUSR1 shows a window;
 - Closing the window doesn't kill the daemon.

**Comment by nwg-piotr** [comment]
Should be doable this way. I didn't assume more than one process. However, the daemon would need to scan `applications` dirs periodically, and die if content change detected, to reflect new or deleted .desktop files on startup. This all will need some effort, spare memory and CPU load.

**Comment by Siborgium** [comment]
> However, the daemon would need to scan `applications` dirs
> and die if content change detected

Killing daemon is not necessary, it could just reload the contents.

> This all will need some effort, spare memory and CPU load.

Yes, but it's not much of a problem: it just sleeps all the time and
wakes up on signal to show the window or on timeout to rescan dirs.

**Comment by nwg-piotr** [comment]
I experimented with this in golang last night, and it looked promising. However, I'm not sure if it should be an option or the only behaviour.
