### ISSUE TITLE
Why is gtk-layer-shell called `gtk-layer-shell-0`?

### ISSUE THREAD

**Issue by colemickens** [nwg-piotr/nwg-launchers#168]
This  breaks pkg-config's ability to discover the system-provided gtk-layer-shell.

aka, it breaks nixpkgs-wayland's build of `nwg-launchers`.

**Comment by colemickens** [comment]
Hm, I do see `gtk-layer-shell` listed as a fallback...

Yeah, that's my mistake. It is a new dependency, that's completely my bad.

**Comment by Siborgium** [comment]
It's the same thing, but for some reason it's named differently. On my machine (Arch Linux x86_64) system-installed gtk-layer-shell is [named gtk-layer-shell-0](https://archlinux.org/packages/community/x86_64/gtk-layer-shell/) in pkg-config, and the same [goes for Ubuntu](https://packages.ubuntu.com/hirsute/libgtk-layer-shell0).
