### ISSUE TITLE
Doesn't use overlay layer, waybar stays visible

### ISSUE THREAD

**Issue by ozls** [nwg-piotr/nwg-launchers#169]
Hello. I know you have shifted your focus towards the Go version, which I totally understand. I tried to switch but I simply prefer nwggrid to nwg-drawer, which has some features I'm not interrested in (like file search or catagories). That being said, I would appreciate if you took the time to look at this.
For some time, nwggrid and nwgbar have not been able to display themselves above waybar, which is not a really big deal but looks a bit glitchy in my case. On the other hand, I can confirm that using nwg-drawer with the -ovl flag works like a charm. Would it be possible to implement this for nwggrid as well?
In any case, a big thank you again for your software!

**Comment by nwg-piotr** [comment]
Hi,

This project is still alive, just the main developer changed. I'm on vacation with no Linux-powered machine, so I can't check your issue myself, but I thought nwggrid to be capable to open on the overlay layer. We need to ask @Siborgium for help.

If it comes to nwg-drawer: if you think that categories and file search should be possible to turn off, just create an issue in the project repository, and I'll take care of this when I'm back home.

**Comment by Siborgium** [comment]
It does use overlay layer, it's just the protocol is a bit more complicated than that. To achieve the desired behaviour, set `-layer-shell-exclusive-zone` option to `-1`.

**Comment by ozls** [comment]
Thanks for looking into this. Using `nwggrid -layer-shell-exclusive-zone=-1` doesn't work for me. Also I forgot to say, I get this error which may be relevant when launching from command line:
```
** (nwggrid:346941): WARNING **: 14:44:33.736: gtk-layer-shell v0.6.0 may not work on GTK v3.24.30.
If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
```
My version of `gtk-layer-shell` is 0.6.0-1, and `gtk3` is 3.24.30-2.

**Comment by nwg-piotr** [comment]
The warning is irrelevant.

**Comment by Siborgium** [comment]
>`Using nwggrid -layer-shell-exclusive-zone=-1` doesn't work for me

Perhaps we should switch to gio's built-in command-line args parser... We use rather simple solution, so the syntax should be as follows: `-layer-shell-exclusive-zone -1`.

**Comment by ozls** [comment]
Works as expected without the equal sign. Thanks a lot for the solution!
