### ISSUE TITLE
nwggrid not respecting nwg-pin-cache order

### ISSUE THREAD

**Issue by ozls** [nwg-piotr/nwg-launchers#176]
Hello! First of all, many many thanks for the server/client update. It works really well, I'm very happy about it.
Unfortunately, I have noticed that nwggrid does not respect the order of my pinned entries since this last update.

This is the content of my .config/nwg-pin-cache:
```
nemo.desktop
Alacritty.desktop
firefox.desktop
telegramdesktop.desktop
signal-desktop.desktop
io.github.quodlibet.QuodLibet.desktop
spotify.desktop
io.gitlab.Goodvibes.desktop
org.manjaro.pamac.manager.desktop
code-settings.desktop
```

And this is what my grid looks like:
![2021-09-18_11-09-1631956075](https://user-images.githubusercontent.com/34961309/133883524-a45783ae-4796-4c08-ac68-9e37400f1d3c.jpg)

It's not that big of a deal, but I wanted to share. Big thanks again for the new development!

**Comment by Siborgium** [comment]
I've managed to find the root of the new problem. Hopefully I'll manage to fix it in the next few days.

**Comment by Siborgium** [comment]
Feel free to try & test, the PR seems to fix the problem.

**Comment by Siborgium** [comment]
Note that the PR is *temporary* fix, and it's probably going to work incorrectly when combined with dynamic content updates.
