### ISSUE TITLE
Utilities fail to start if a stale pid file is present

### ISSUE THREAD

**Issue by alebastr** [nwg-piotr/nwg-launchers#178]
Output:
```
% nwgbar
INFO: wm: sway
INFO: 4 bar entries loaded
INFO: Using css file '"/home/alebastr/.config/nwg-launchers/nwgbar/style.css"'
ERROR: process with specified pid does not exist
% ls $XDG_RUNTIME_DIR/nwgbar*
/run/user/1000/nwgbar.pid  /run/user/1000/nwgbar.pid.lock
% cat $XDG_RUNTIME_DIR/nwgbar.pid
9219%
% ps aux |grep 9219 |grep -v grep
```

Steps to reproduce:
a) synthetic - kill nwgbar with SIGKILL
b) natural - somehow I got that _once_ when logging out from sway via nwgbar. Will update if I find exact steps to reproduce.

**Comment by Siborgium** [comment]
I agree. The way it works is quite cumbersome, so changing it to something more sensible won't hurt, I guess.

**Comment by Siborgium** [comment]
This fix the synthetic case. Ping me if this doesn't work for you or you discover the steps required to reproduce the natural case.
