### ISSUE TITLE
Bigger Icons on nwggrid?

### ISSUE THREAD

**Issue by Figuera** [nwg-piotr/nwg-launchers#180]
Currently the size of the icons is limited to 256 pixels (8 bit integer?).

I wish to use bigger icons. I guess my use case is not the main focus of the project (I am using it as a game launcher, not an ordinary menu) but I don't immediately see why there such a limitation would be necessary.

**Comment by Siborgium** [comment]
>I wish to use bigger icons. I guess my use case is not the main focus of the project (I am using it as a game launcher, not an ordinary menu)

While it's not the main focus of the project, we do support such usecases.

>Currently the size of the icons is limited to 256 pixels (8 bit integer?).

>8 bit integer

No, it's just nobody ever asked for more. We need to have some sensible max size to fail early with nice error message if the icon size is set to some unrealistically large value though.

What icon size do you want to use?

**Comment by Figuera** [comment]
I was going for 288 (4x original size) but I might test something even
bigger if possible. I guess 512 (2 lines in a Full HD monitor) is not
unreasonable.

If it were possible to scroll horizontally, I could use anything up to 1000
(1 icon per screen in a full hd screen).

**Comment by Siborgium** [comment]
This should do the trick. I'm going to publish 0.6.2 this Sunday, this commit will be there. Feel free to report any issues :)

**Comment by Figuera** [comment]
It works:

`-s 412`:

![2021-09-29_14-09-1632939444_screenshot](https://user-images.githubusercontent.com/703016/135326356-25bf4ebf-42cd-481f-b72b-5ca65c4c4712.png)

I must confess I got used to, and might stick with, the previous size, `-s 256`:

![2021-09-29_14-09-1632939460_screenshot](https://user-images.githubusercontent.com/703016/135326250-c5711d7a-008e-46c4-b1b4-aeb23f811bcb.png)

**Comment by Figuera** [comment]
### Icons scrolls nicely even if I exceed my vertical pixel count:

`-s 2048´:

https://user-images.githubusercontent.com/703016/135327860-3610c757-7b1d-4f56-8d3c-176a566482b6.mp4

So I can confirm that #182 is working

### Icons do not break nicely if I request size bigger than maximum:

`-s 2160`:

![2021-09-29_14-09-1632940342_screenshot](https://user-images.githubusercontent.com/703016/135328100-9256ac39-ba6c-4cf2-8748-06f2e5da8feb.png)

Is this the expected behavior? I would expect it to either default to the maximum (2048) or show nothing but some kind of error message.

**Comment by Siborgium** [comment]
>Is this the expected behavior?

It is, that's how it has been working for a long time.

>I would expect it to either default to the maximum (2048) 

Agreed, this is surely better than the current behaviour.

>show nothing but some kind of error message.

Actually, we do print a lot of "soft" errors, not terminating the application when encountered. I am thinking about making some of them "hard", but for now let's stick with the former option.

**Comment by Figuera** [comment]
I do see the warning if I launch from the terminal, unfortunately when I first encountered the error I was mapping it to a keybind in sway. So it took me a while to identify the problem.

To be honest, now the max size is too large so I expect this not to be a recurring problem.

**Comment by Siborgium** [comment]
>I do see the warning if I launch from the terminal,

Yeah, and there's a lot of warnings, so it's hard to see which are important and which are not. This is confusing, that's why I've mentioned it.

I'll merge the #189 to master later today. Quick tests show no problems so far.
