### ISSUE TITLE
slow launch time :[

### ISSUE THREAD

**Issue by minugithub** [nwg-piotr/nwg-launchers#193]
~ 160 ms from Terminator , a bit too slow :[ how could make better?
Tried preload mechanisms outlined in Arch Wiki, but without any success. How is possible?

I recommend adding to CSS:
`*{transition:all .33s cubic-bezier(.21,.33,.77,1);outline:0}`
can at least make the hover color change effect smooth and fancy, and remove that nasty dotted accessibility border.

Full CSS I use for my grid:
`*{border-radius:0;transition:all .33s cubic-bezier(.21,.33,.77,1);font-weight:700;font-family:Quicksand;font-size:14px;outline:0}box{margin:6px}#searchbox{background:0;border-color:#777;border-width:3px;color:#f7f7f7;padding:6px;border-radius:33px;margin:6px}#commands{padding:6px}`

Tried using CSS scale:0.9 and transition to 1.0 on hover, to make cool bouncy effect, but didnt work.. did I accidently mess it up, or is it by design? CSS3 could allow some amazing effects.

But all in all - I absolutely love this app. Thanks!

**Comment by minugithub** [comment]
Seems the slowdown is caused by the amount of .desktop files in my application directory, as is most logical.
But - i now figured out how to use **nwggrid-server** and it's perfectly quick. Thanks so much, good luck!

**Comment by Siborgium** [comment]
I think it's okay to close the issue now :)
