### ISSUE TITLE
nwgbar: Class Styling

### ISSUE THREAD

**Issue by Figuera** [nwg-piotr/nwg-launchers#195]
Feature request:

Would it be possible to add a class property to buttons? So it is possible to do something like:

JSON
```
  {
    "name": "_Lock screen",
    "exec": "swaylock",
    "icon": "system-lock-screen",
    "class": "lockscreen"
  },
```
CSS:
```
button.lockscreen {
    background-color: red;
}
```

**Comment by Siborgium** [comment]
Sure, this seems doable.

**Comment by Siborgium** [comment]
As far as I could test, it works fine. Sorry for the delay, my schedule's rather tight at the moment. Feel free to try `nwg-launchers-git`. Once I'll deal with #194 , it'll go into the 0.6.4

**Comment by Figuera** [comment]
Thank you for that, unfortunately I am temporarily without access to my Linux machine. I will get back to you with testing as soon as I can.

**Comment by Figuera** [comment]
I'm finally back and yeah. Running smoothly and as expected.
