### ISSUE TITLE
config dir invalid

### ISSUE THREAD

**Issue by fhdk** [nwg-piotr/nwg-launchers#2]
https://github.com/nwg-piotr/nwg-launchers/blob/5e5808a1c5b0d07d89a7aac42bb1db1a07b19abf/grid/grid_tools.cpp#L56

The code creates a path $HOME`/.config/.config/nwggrid` which of course don't exist

**Comment by nwg-piotr** [comment]
You're right: I replaced one bug with another one. Thanks for reporting. I wouldn't notice soon, as I'm on Arch + sway at the moment, with no `$XDG_CONFIG_HOME` set. Can't check at the moment, but it should be OK now.

**Comment by nwg-piotr** [comment]
It seems I fixed the bug in nwgbar and nwgdmenu, but not in nwggrid. I'll take a closer look later tonight.

**Comment by nwg-piotr** [comment]
Additionally tested on Debian, still works well. Closing.
