### ISSUE TITLE
Graphics glitches in the current git version

### ISSUE THREAD

**Issue by Figuera** [nwg-piotr/nwg-launchers#201]
The current git version of the program is exhibiting some weird graphical glitches in my computer:

- nwg-launchers-git-r575.4dde40e-1: (The current master branch version)

![2022-01-06_23-01-1641530760_partial](https://user-images.githubusercontent.com/703016/148493469-dffb28ba-4fa9-431e-b8d3-cb7ddcb9a413.png)

- nwg-launchers 0.6.3-1: (The latest stable release)

![2022-01-06_23-01-1641530842_partial](https://user-images.githubusercontent.com/703016/148493547-cb7267c9-77d3-48d9-960d-0f813b55715a.png)

nwg-bar is the one with the most glaring glitches, but I can also see white borders on the icons of nwg-grid that are not by design. Everything is fixed if I use the stable version of software. 

I am aware that the development version is not supposed to be stable and maybe the developers are aware of the problem already so please feel free to close and ignore if necessary.

**Comment by Siborgium** [comment]
Thanks for the issue! It is indeed a problem, although I am not sure exactly what change it is caused by. I think I've fixed the issue on my machine. Please, let me know if the linked pull request works for you.

**Comment by Siborgium** [comment]
Let's assume it *did* work.
