### ISSUE TITLE
Error when launching programs located in home directory

### ISSUE THREAD

**Issue by absolutelynothinghere** [nwg-piotr/nwg-launchers#205]
Tried using `nwggrid` to launch programs whose binaries are in the home directory and failed. The respective `.desktop` files contain any of the following:

```desktop
Exec=~/path/to/program %F
Exec=~/path/to/program "%F"
Exec=${HOME}/path/to/program %F
Exec=${HOME}/path/to/program "%F"
Exec=sh -c "~/path/to/program %F"
```

Either of these lines produces the error "no such file or directory", except the last line which produces "Text ended before matching quote was found".

**Comment by Siborgium** [comment]
I've added ~/ expansion, and it seems to work on my machine. Please let me know if it helps you.

**Comment by Siborgium** [comment]
Please reopen if the problem is still not fixed.
