### ISSUE TITLE
nwggrid does not stick to consistent icon theme

### ISSUE THREAD

**Issue by scotabroad** [nwg-piotr/nwg-launchers#211]
While using Hyprland on NixOS, I compiled nwg-launcher from source (as the nixpkgs one in nixos-unstable is outdated and lacks support for svgs). However, I observe different behaviour when I launch nwggrid using my custom keybind (ALT_L+R) and when I activate it via a custom waybar module. Both execute the same command `pkill nwggrid || nwggrid` (so I can toggle nwggrid on and off), however only the waybar module will display with my icon theme. The keybind will display the default icon for each app (probably the hicolor theme for most apps). 

Here is nwggrid as executed from the waybar module:

![20221026_17h59m03s_grim](https://user-images.githubusercontent.com/65510090/198170138-6e0ef705-1035-4332-9b12-2af108b54833.png)

Here is nwggrid as executed from the keybind (or by launching `nwggrid` from my terminal):

![20221026_17h59m14s_grim](https://user-images.githubusercontent.com/65510090/198170283-7214de04-4973-483d-8724-3a4618a6e7f6.png)

Any ideas why they would be different?

**Comment by Siborgium** [comment]
>However, I observe different behaviour when I launch nwggrid using my custom keybind (ALT_L+R) and when I activate it via a custom waybar module. Both execute the same command pkill nwggrid || nwggrid (so I can toggle nwggrid on and off), however only the waybar module will display with my icon theme. 

I am barely familiar with the NixOS, unfortunately. The described behaviour is likely to be caused by `GTK_THEME` having different values. You could check it by prepending `env > /tmp/env.txt || ` to your keybind command and then grepping specified file for `GTK_THEME`.

**Comment by Siborgium** [comment]
On a side note: you may want to spawn nwggrid-server at startup and then issue `nwggrid -client` to display grid window -- it's much faster than spawning a new instance each time. This would not let you use your keybind to close the window, but you could use Esc. I can implement closing the window by `nwggrid -client`, if it is important for you.

**Comment by Siborgium** [comment]
>I can implement closing the window by nwggrid -client, if it is important for you.

Feel free to try #213, it does exactly that.

**Comment by scotabroad** [comment]
The problem turned out to be that waybar would set the `GDK_PIXBUF_MODULE_FILE` variable in its environment, but this was not set in the environment of Hyprland. I have since made sure that my Hyprland also has this variable so that icons are consistent.

With the topic of the being able to toggle `nwggrid -client` on and off from one keybind, I will look into #213. For now, as my icon issue is solved, I am closing this issue.
