### ISSUE TITLE
nwg-bar shortcut config issue

### ISSUE THREAD

**Issue by akrram09** [nwg-piotr/nwg-launchers#232]
it would be better if you can apply wlogout style of shortcuts config in the config because its so limited even i cant press Lock shortcut because Logout has the same name and i have to add a letter to logout and it will show in the app here is how wlogout work

> {
    "label" : "lock",
    "action" : "swaylock -f -c 000000",
    "text" : "Lock",
    "keybind" : "l"
}
{
    "label" : "hibernate",
    "action" : "systemctl hibernate",
    "text" : "Hibernate",
    "keybind" : "h"
}
{
    "label" : "logout",
    "action" : "loginctl terminate-user $USER",
    "text" : "Logout",
    "keybind" : "e"
}
{
    "label" : "shutdown",
    "action" : "systemctl poweroff",
    "text" : "Shutdown",
    "keybind" : "s"
}
{
    "label" : "suspend",
    "action" : "systemctl suspend",
    "text" : "Suspend",
    "keybind" : "u"
}
{
    "label" : "reboot",
    "action" : "systemctl reboot",
    "text" : "Reboot",
    "keybind" : "r"
}

**Comment by nwg-piotr** [comment]
This is not a wlogout replacement. This is just a button bar, with a command attached to each button. Button images and commands are up to the user, and I don't care about them.
