### ISSUE TITLE
Standardize Makefiles

### ISSUE THREAD

**Issue by ericonr** [nwg-piotr/nwg-launchers#30]
Hey there! I just packaged sgtk-menu for Void (which it seems you also use?) and was looking to package nwg-launchers as well, because I wanted to give them a test drive before making actual PRs for them.

Do you think it would be possible to make the Makefiles more standard? Furthermore, having to manually run each one is a pain for packaging in Void, but I fixed that part with a simple script:

```
#!/usr/bin/env bash

for dir in bar dmenu grid
do
	cd $dir
	make "$@"
	cd ..
done
```

However, using `CC` set to `g++` is a bit of an anti-pattern, as well as the way you're outputing pkg-config stuff. As it stands, the only one that built cleanly without any patching was the `bar` one. Would you be open to PRs for fixing some of these issues? I'd also be interested in adding a toplevel makefile, because a script feels a little flimsy.

**Comment by nwg-piotr** [comment]
Hi,

nwg-lauchers is the one and only code I've ever written in C++, and I'm still damned lost in the world of pointers and references. If you can improve the makefile, I'll be glad, and try to learn something new by the way. However, I'm not sure how to satisfy the `nlohmann-json` dependency. The package is missing from the Void repository.

**Comment by ericonr** [comment]
I don't have much experience with C++ either, my thing is more C :p . That said, references are cooler than pointers and I wish C had them.

The JSON parser is provided by the `json-c++` library in Void.

**Comment by santouits** [comment]
May I suggest that instead of manually writing Makefiles, to use autotools to create them, or even better to use meson, as sway does. I could help.

**Comment by nwg-piotr** [comment]
Feel free to make a PR. In case you used meson, it would be good to include nlohmann-json, as described [here](https://github.com/nlohmann/json#integration). The package is unavailable in some distros, e.g. Void Linux.
