### ISSUE TITLE
Nwggrid mode to pin programs in any place you like

### ISSUE THREAD

**Issue by ghost** [nwg-piotr/nwg-launchers#31]
As I have not found a worthy replacement for https://github.com/Zren/plasma-applet-tiledmenu that isn't applet I want to suggest a feature for nwggrid. It's an expansion to favourites, I do not need tiles, groups, sidebar search or other features from that project.

It could be two modes. _nwggrid -m default_ is just like today .

_nwggrid -m fixed_ could start the menu as a full screen blank grid (until you pin programs) with the same search bar. The important distinction here is that you have freedom to move and pin programs in any place of the entire screen grid. I pin more than 50 programs and scripts, with icon size 48, called from .desktop. When you start typing it search the entire program list, not just from pins.
I once tried to make wayland grid with Python and drag operations crashed my computer or window manager. It was ugly. So could pin with right click no problem or just text file. Changing icon size might mess up the position of saved items. 

Good job on the grid, it opens instantly on high number of programs even without daemon.

**Comment by nwg-piotr** [comment]
I don't see a way to modify the existing code to work this way. The only I could do would be to add pin/unpin action (e.g. on right click), and display pinned items above the list, instead or above most used items. No drag-and-drop, no fixed positions.

**Comment by nwg-piotr** [comment]
Reopening: the simple pin / unpin action (as described above) in development.
