### ISSUE TITLE
Portability tracker

### ISSUE THREAD

**Issue by santouits** [nwg-piotr/nwg-launchers#36]
Let's track here what has to be done to make the launchers more portable to different systems.

We discussed some things in the other PR:

The wrapper scripts inside /usr/lib/nwg* folders should be removed and the launchers will reside inside the bin directory, in whatever prefix we install them. Let's say that we install them to prefix /usr. That means the files will be:
```
/usr/bin/nwgbar
/usr/bin/nwgdmenu
/usr/bin/nwgdmenu_run // a wrapper script that executes nwgdmenu manually
/usr/bin/nwggrid
```

Also there are many paths that are hardcoded inside the code like 
```
 fs::copy_file("/usr/share/nwgbar/style.css", target, fs::copy_options::overwrite_existing);
```

**Comment by nwg-piotr** [comment]
> there are many paths that are hardcoded inside the code

The `overwrite_existing` option is misleading, as the file should only be copied if not found. This does not necessarily need to be done programmatically, provided that Meson allows to copy file **if not found**. Does it? We don't want to overwrite user-modified styles and templates.

**Comment by nwg-piotr** [comment]
The first part of TODOs done in #40.

1. No more scripts to launch commands placed in /usr/lib. All commands moved to the bin folder.
2. No need to use `nwgdmenu_run` script. `<some_command> | nwgdmenu` builds dmenu out of stdin input. 

```
$ ls | nwgdmenu
```

![screenshot](http://nwg.pl/Lychee/uploads/big/28b7b3dab3b6fe8c5f4b16228e0e45d3.png)

The `nwgdmenu` command standalone builds the menu out of commands found in $PATH, as primary `nwgdmenu_run` did.

**Comment by santouits** [comment]
Nice, so nwgdmenu_run is not needed at all.

About the style.css, maybe it should be better to not copy the file at all, and let the user do it if they want and just check if it exists then use the user's config otherwise use the one in the share directory.

About the question, with meson you can do anything you can do in bash because it allows you to write a custom install script that it runs after the installation.

I say we leave those in place for the time and remove them after we merge the meson PR. I'll update that later.

**Comment by nwg-piotr** [comment]
> About the style.css, maybe it should be better to not copy the file at all, and let the user do it if they want and just check if it exists then use the user's config otherwise use the one in the share directory.

I've been thinking about it since yesterday: just wanted to be user friendly. However, if we need to give up on this in favour of portability - let it be. If I understood well: not necessarily now, but in "further development", right?

**Comment by santouits** [comment]
I left it as it is, and fixed the hardcoded paths in the meson PR.
