### ISSUE TITLE
C++ vs Python menus

### ISSUE THREAD

**Issue by epsilon-0** [nwg-piotr/nwg-launchers#38]
Which one would be the one getting more support into the future?

I want to package both for gentoo and would love to know which one to give a preference to.

**Comment by nwg-piotr** [comment]
LOL, hard question! Personally I use nwg-launchers, but sgtk-menu is not going to be abandoned for at least 3 reasons:

1. it still receives feedback and feature request;
2. it contains the menu command, which I'm not going to reproduce in C++ as long, as [this issue](https://github.com/nwg-piotr/sgtk-menu/issues/1) stays unresolved;
3. I do like python. :)

**Comment by epsilon-0** [comment]
No worries :smiley_cat: 
Thanks a lot for making this.

**Comment by nwg-piotr** [comment]
Great that you like it.
