### ISSUE TITLE
nwggrid: style.css being used instead of the custom css

### ISSUE THREAD

**Issue by nwg-piotr** [nwg-piotr/nwg-launchers#41]
Started to happen after merging #35 

> $ nwgbar -o 0 -v -ha l -s 48 -c dock.css -t dock.json
ERROR: Template file not found, using default

@santouits

**Comment by ericonr** [comment]
It doesn't seem to error out the second time you run it... Where was it supposed to find the default template?

**Comment by nwg-piotr** [comment]
Also the `/home/piotr/.config/nwg-launchers/nwgbar/style.css` file is being used instead of the custom css.

**Comment by nwg-piotr** [comment]
Alright, I haven't realized that the config dirs have been moved into `~/.config/nwg-launchers`. Anyway, I'm still having some issues w/ the css.file. Template is ok.

**Comment by nwg-piotr** [comment]
Alright, dunno how to link it properly, so I'll just leave it here:

`bar.cc` lines 192 - 194: the `custom_css` variable has been replaced with `custom_css_file`, which is a mistake. The `custom_css` string holds full path. Lines 192-194 should be reverted to their previous state.
