### ISSUE TITLE
fatal error: ../nwgconfig.h: No such file or directory

### ISSUE THREAD

**Issue by tukusejssirs** [nwg-piotr/nwg-launchers#46]
I've just wanted to try out your launcher/grid, but following your instructions from the `README.md` file I get a fatal error.

I am on Fedora 32 and here's what I did:

```bash
sudo dnf -y install gtkmm30-devel json-devel
git clone git@github.com:nwg-piotr/nwg-launchers.git
cd nwg-launchers/grid
sudo make clean install
```

And the last command (`make`) output is as follows:

```bash
$ sudo make clean install
rm -rf *.o nwggrid
g++ -c -Wall -O2 -std=c++17 grid.cc -o grid.o `pkg-config gtkmm-3.0 --libs --cflags`
In file included from grid.cc:10:
grid.h:9:10: fatal error: ../nwgconfig.h: No such file or directory
    9 | #include "../nwgconfig.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:15: grid.o] Error 1
```

There is no such file as `nwgconfig.h` in the repo root.

For the repo looks like it should be built with `meson` and not with `make`, I did the following:

```bash
sudo dnf -y install gtkmm30-devel json-devel meson ninja
git clone git@github.com:nwg-piotr/nwg-launchers.git
cd nwg-launchers
meson build
ninja -C build
sudo ninja -C build install
```

And this successfully installed all three programs: `nwgbar`, `nwgdmenu`, `nwggrid`.

I might be a good idea to update the instructions in `README.md`. :smiley:

**Comment by nwg-piotr** [comment]
Sorry, the PR was merged last night at 4 am, and it was too late to update README. Will be done ASAP.

**Comment by santouits** [comment]
Should I make a PR with the instructions and you can change it later?

**Comment by nwg-piotr** [comment]
It would be great. Could you please take into account also dependencies, clear and uninstall?

**Comment by tukusejssirs** [comment]
Also it would be nice if `build/` would be added to `.gitignore` as IMO it is the usual name for the build folder. Currently, when I build the program(s) the way I described in the OP, `git` would treat that folder as untracked.

**Comment by ericonr** [comment]
The current examples are using `builddir/`, which is in `.gitignore`.

**Comment by tukusejssirs** [comment]
I see, but I still think that `build` is more widely used than `builddir`.

**Comment by santouits** [comment]
We could have both with a wildcard like build* to .gitignore. Make a PR for it. I like builddir more in the examples because it shows it is a directory name and can be replaced with anything and not a command to people who don't know, but yeah build is more used.
