### ISSUE TITLE
Feture request: add a key to clear the search widget

### ISSUE THREAD

**Issue by tukusejssirs** [nwg-piotr/nwg-launchers#47]
I'd like to be able to select all text (written by me) when I press <kbd>Ctrl</kbd>+<kbd>A</kbd>, both in `nwgdmenu` and `nwggrid`.

Currently, when I press that shortcut, it outputs `a` as if I haven't press <kbd>Ctrl</kbd>.

**Comment by nwg-piotr** [comment]
You mean the search box? Actually you're not writing anything in there. The widget is disabled and read-only, updated programmatically on the key press event. I did it to allow the user not to care about the widget focus and speed up searching in keyboard-oriented workflow. I'm afraid it makes your request impossible.

**Comment by santouits** [comment]
Why would you want to select it all? for delete? If yes maybe a shortcut for deleting everything with delete button can be added if it is considered useful.

**Comment by tukusejssirs** [comment]
> Why would you want to select it all? for delete?

Indeed, for delete or overwriting the search pattern. Sometimes it happens to me that I search for something that does not match anything, therefore I want to search a different pattern, prior to which I am accustomed to select all the text and then type the new pattern. :smiley:

> If yes maybe a shortcut for deleting everything with delete button can be added if it is considered useful.

Well, a _button_ that must be clicked with a mouse button is not a solution for me as it would require me to reach for a mouse. I am mostly a keyboard guy, that's why for me it is much easier to press a keyboard shortcut than reach for a mouch/touchpad/whatever, move it to the place the button is located, press the button and move my hand back onto the keyboard.

**Comment by santouits** [comment]
no I meant a shortcut which deletes everything when you press the delete button on your keyboard. I think it is not used anyway in anything.

**Comment by nwg-piotr** [comment]
This should be doable.

**Comment by tukusejssirs** [comment]
Aaah, well if by button you mean a key, then yes, that would be great! It might be a good idea to let the user customise the keybinding/shortcut.

**Comment by nwg-piotr** [comment]
> It might be a good idea to let the user customise the keybinding/shortcut

For now let it be a predefined key. I wouldn't like to add a config file for just a single option.
