### ISSUE TITLE
1.0.0 roadmap

### ISSUE THREAD

**Issue by nwg-piotr** [nwg-piotr/nwg-launchers#52]
I used to plan on 1.0.0 release after the fourth launcher - the [sgtk-menu](https://github.com/nwg-piotr/sgtk-menu#system-menu-w-favourites-above-and-custom-appendix-below) counterpart - is developed. However, the [menu overflow issue](https://github.com/nwg-piotr/sgtk-menu/issues/1) on sway remains unresolved, and coding the [insane workaround](https://github.com/nwg-piotr/sgtk-menu/pull/5) I used in python again in C++ would be a nightmare to me. Moreover, the menu looks well, but I don't use it at all since the grid appeared. That's why I thought to go ahead with the 1.0.0 release, and leave the menu for an undefined future - if any.

IMO we could find this project 1.0.0-ready as soon as the [changes](https://github.com/nwg-piotr/nwg-launchers/pull/44#issuecomment-655667343) @ericonr is going to make are done.

Let me know what you think.

**Comment by ericonr** [comment]
What else are you looking to develop now? Mostly the feature requests?

**Comment by nwg-piotr** [comment]
Having given up on .desktop-based menu, I have no specific idea at the moment. Feature request and bug hunting. BTW: today at the office I discovered, that nwgdmenu, launched from a key binding, improperly detects stdin input - provided that sway has been started from gdm. Complicated, isn't it? Fixing this is the plan for tonight.

**Comment by nwg-piotr** [comment]
@ericonr - are you done with the changes you planned? If so, I'd focus on testing and a release this weekend.

**Comment by ericonr** [comment]
@nwg-piotr sorry, didn't get the time for them yet! If you'd like to cut a release, go ahead. It's probably best not to delay this because of these changes now.

**Comment by nwg-piotr** [comment]
No problem. This may always be a minor release.
