### ISSUE TITLE
'nwggrid' terminated by signal SIGABRT

### ISSUE THREAD

**Issue by lemniskett** [nwg-piotr/nwg-launchers#60]
I installed nwg-launchers from the AUR

when i launch `nwggrid`, it doesn't launch and it outputs this error
```
WM: sway
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
fish: 'nwggrid' terminated by signal SIGABRT (Abort)
```

tried building from master, the issue still persists.
`nwgbar` and `nwgdmenu` work as intended.

**Comment by nwg-piotr** [comment]
This may be damned difficult to debug, as nobody else reported such the error so far... :/

**Comment by nwg-piotr** [comment]
Could you tell me what your `$LANG` variable looks like?

**Comment by lemniskett** [comment]
It is empty, i set it to `us` and now it works!

**Comment by nwg-piotr** [comment]
Great! I'll need to catch this error, by the way.
