### ISSUE TITLE
Slow start up

### ISSUE THREAD

**Issue by gustavo-hms** [nwg-piotr/nwg-launchers#73]
Hi! First of all, I like this project. Both `nwggrid` and `nwgbar` are useful tools. However, when I launch `nwggrid`, it takes about 2 seconds to show something on the screen, making a somewhat poor user experience.

Do you experience the same issue? Or perhaps there's something wrong with my configuration?

I'm using Sway on Manjaro.

Thanks!

**Comment by nwg-piotr** [comment]
Hi. Two things may elongate the startup: a lot of .desktop files and heavy icon theme. On my machine w/ 117 desktop entries and Papirus-Light theme it takes nwggrid 200 - 250 ms to launch.

**Comment by gustavo-hms** [comment]
I was using Breeze Icon Theme, but switched to Papirus-Light just to test the hypothesis, and the startup time didn't change noticeably.

Also, my `/usr/share/applications` contains 203 `.desktop` files, while `~/.local/share/applications` lists just 2 and `/usr/local/share/applications` is nonexistent. It shouldn't take too long.

I just noticed that, running `nwggrid` from the terminal, it prints 
```
548 .desktop entries found
```
It's more than 2.5 times the number I was expecting. Is there any other place where it's looking for `.desktop` files?

**Comment by nwg-piotr** [comment]
Take a lok at this: https://github.com/nwg-piotr/nwg-launchers/blob/43f7d5a21715f13f0b5c36529f6f407fc9fbb35a/grid/grid_tools.cc#L86

Duplicates should be omitted in your results, but they are being read every time you launch nwggrid.
