### ISSUE TITLE
How do I change the background color?

### ISSUE THREAD

**Issue by bernharl** [nwg-piotr/nwg-launchers#85]
I'd like to make nwggrid and nwgbar fit with a light theme and I can't seem to find how to change the background color. The icons of my light theme look terrible with the default black background.

**Comment by nwg-piotr** [comment]
As for now you can only change the background opacity, and the colour is always black. I've never felt such a need, but it should be quite easy to add the background colour as the command argument. I'll try to do it soon.

**Comment by bernharl** [comment]
Thanks for the quick reply!

Another fix for my specific issue would be the ability to force nwggrid to use a specific theme (or just the dark version of the current GTK theme). 

I could do that by setting environment variables when running it, but those variables then get adopted by all applications I run with nwggrid.

**Comment by nwg-piotr** [comment]
As my default colour is always black, I think adding an argument is the simplest way. I'll take a closer look when I'm back (this weekend).

**Comment by nwg-piotr** [comment]
I'd be grateful for feedback. As you seem to use Arch, you may simply install `nwg-launchers-git`.
