### ISSUE TITLE
nwggrid: flatpaks are not listed

### ISSUE THREAD

**Issue by GabMus** [nwg-piotr/nwg-launchers#93]
As the title says. sgtk-grid does list flatpaks, maybe it's something you want to implement.

By the way, very nice suite of apps, I'm really enjoying using them. Keep it up!

**Comment by nwg-piotr** [comment]
Thanks!

If it comes to flatpak, I haven't used it ever in my life. Possibly it could be taken into account in further development.

**Comment by nwg-piotr** [comment]
It should work now. Could you please install from the `master` branch (or the -git package in case you use Arch BTW) and check?

**Comment by GabMus** [comment]
Thanks for the quick reply. I tried your latest patch and it didn't work, so I had a look at your code, the problem seemed to be the tilde in the path.

I created a PR fixing this issue, as well as making that little bit of code a little more clean.
