### ISSUE TITLE
nwgdmenu leaves PID file behind.

### ISSUE THREAD

**Issue by ericonr** [nwg-piotr/nwg-launchers#96]
It certainly doesn't take up too much space, but it's a bit ugly. Is it necessary for the file to live beyond the application? I'm messing around in that code right now, so if you have an idea of what you'd like to do, I can implement it.

**Comment by nwg-piotr** [comment]
You mean the file location?

I tried couple of ways to avoid multiple instances, and the latter seems to work not bad. However, if you have an idea on how to improve it, feel free submit a PR.
